
let aguadebeber = {
    musica: "Água de Beber",
    artista: "Tom Jobim",
    letra: [
        "Eu quis amar, mas tive medo",
        "E quis salvar meu coração",
        "Mas o amor sabe um segredo",
        "O medo pode matar o seu coração",
        "Água de beber",
        "Água de beber, camará",
        "Água de beber",
        "Água de beber, camará",
        "Eu nunca fiz coisa tão certa",
        "Entrei pra escola do perdão",
        "A minha casa vive aberta",
        "Abri todas as portas do coração",
        "Água de beber",
        "Água de beber, camará",
        "Água de beber",
        "Água de beber, camará",
        "Eu sempre tive uma certeza",
        "Que só me deu desilusão",
        "É que o amor é uma tristeza",
        "Muita mágoa, demais para um coração",
        "Água de beber",
        "Água de beber, camará",
        "Água de beber",
        "Água de beber, camará"
    ]
}
let chovechuva = {
    musica: "Chove Chuva",
    artista: "Jorge Ben Jor",
    letra: [
        "Chove chuva",
        "Chove sem parar",
        "Chove chuva",
        "Chove sem parar",
        "Pois eu vou fazer uma prece",
        "Pra Deus, nosso Senhor",
        "Pra chuva parar",
        "De molhar o meu divino amor",
        "Que é muito lindo",
        "É mais que o infinito",
        "É puro e belo",
        "Inocente como a flor",
        "Por favor, chuva ruim",
        "Não molhe mais",
        "O meu amor assim",
        "Por favor, chuva ruim",
        "Não molhe mais",
        "O meu amor assim",
        "Chove chuva",
        "Chove sem parar",
        "Chove chuva",
        "Chove sem parar",
        "Pois eu vou fazer uma prece",
        "Pra Deus, nosso Senhor",
        "Pra chuva parar",
        "De molhar o meu divino amor",
        "Que é muito lindo",
        "É mais que o infinito",
        "É puro e belo",
        "Inocente como a flor",
        "Por favor, chuva ruim",
        "Não molhe mais",
        "O meu amor assim",
        "Por favor, chuva ruim",
        "Não molhe mais",
        "O meu amor assim",
        "Chove chuva",
        "Chove sem parar",
        "Chove chuva",
        "Chove sem parar"
    ]
}
let aguasdemarco = {
    musica: "Águas de Março",
    artista: "Tom Jobim",
    letra: [
        "É pau, é pedra, é o fim do caminho",
        "É um resto de toco, é um pouco sozinho",
        "É um caco de vidro, é a vida, é o Sol",
        "É a noite, é a morte, é o laço, é o anzol",
        "É peroba do campo, é o nó da madeira",
        "Caingá, candeia, é o Matita Pereira",
        "É madeira de vento, tombo da ribanceira",
        "É o mistério profundo, é o queira ou não queira",
        "É o vento ventando, é o fim da ladeira",
        "É a viga, é o vão, festa da cumeeira",
        "É a chuva chovendo, é conversa ribeira",
        "Das águas de março, é o fim da canseira",
        "É o pé, é o chão, é a marcha estradeira",
        "Passarinho na mão, pedra de atiradeira",
        "É uma ave no céu, é uma ave no chão",
        "É um regato, é uma fonte, é um pedaço de pão",
        "É o fundo do poço, é o fim do caminho",
        "No rosto, o desgosto, é um pouco sozinho",
        "É um estrepe, é um prego, é uma ponta, é um ponto",
        "É um pingo pingando, é uma conta, é um conto",
        "É um peixe, é um gesto, é uma prata brilhando",
        "É a luz da manhã, é o tijolo chegando",
        "É a lenha, é o dia, é o fim da picada",
        "É a garrafa de cana, o estilhaço na estrada",
        "É o projeto da casa, é o corpo na cama",
        "É o carro enguiçado, é a lama, é a lama",
        "É um passo, é uma ponte, é um sapo, é uma rã",
        "É um resto de mato, na luz da manhã",
        "São as águas de março fechando o verão",
        "É a promessa de vida no teu coração",
        "É uma cobra, é um pau, é João, é José",
        "É um espinho na mão, é um corte no pé",
        "São as águas de março fechando o verão",
        "É a promessa de vida no teu coração",
        "É pau, é pedra, é o fim do caminho",
        "É um resto de toco, é um pouco sozinho",
        "É um passo, é uma ponte, é um sapo, é uma rã",
        "É um belo horizonte, é uma febre terçã",
        "São as águas de março fechando o verão",
        "É a promessa de vida no teu coração",
        "Pau, edra, im, inho",
        "Esto, oco, ouco, inho",
        "Aco, idro, ida, ol, oite, orte, aço, zol",
        "São as águas de março fechando o verão",
        "É a promessa de vida no teu coração",
    ]
}
let pelaluzdosolhosteus = {
    musica: "Pela Luz Dos Olhos Teus",
    artista: "Tom Jobim",
    letra: [
        "Quando a luz dos olhos meus",
        "E a luz dos olhos teus",
        "Resolvem se encontrar",
        "Ai, que bom que isso é, meu Deus",
        "Que frio que me dá o encontro desse olhar",
        "Mas se a luz dos olhos teus",
        "Resiste aos olhos meus",
        "Só pra me provocar",
        "Meu amor, juro por Deus, me sinto incendiar",
        "Meu amor, juro por Deus",
        "Que a luz dos olhos meus já não pode esperar",
        "Quero a luz dos olhos meus",
        "Na luz dos olhos teus",
        "Sem mais lá-rá-rá-rá",
        "Pela luz dos olhos teus",
        "Eu acho, meu amor, que só se pode achar",
        "Que a luz dos olhos meus precisa se casar",
        "Quando a luz dos olhos meus",
        "E a luz dos olhos teus",
        "Resolvem se encontrar",
        "Ai, que bom que isso é, meu Deus",
        "Que frio que me dá o encontro desse olhar",
        "Mas se a luz dos olhos teus",
        "Resiste aos olhos meus",
        "Só pra me provocar",
        "Meu amor, juro por Deus, me sinto incendiar (me sinto incendiar)",
        "Meu amor, juro por Deus",
        "Que a luz dos olhos meus já não pode esperar",
        "Quero a luz dos olhos meus",
        "Na luz dos olhos teus",
        "Sem mais lá-rá-rá-rá",
        "Pela luz dos olhos teus",
        "Eu acho, meu amor, e só se pode achar",
        "Que a luz dos olhos meus precisa se casar",
        "Que a luz dos olhos meus precisa se casar",
        "Que a luz dos olhos meus precisa se casar",
        "Precisa se casar (precisa se casar)",
        "Precisa se casar (precisa se casar)",
        "Precisa se casar, precisa se casar",
        "Precisa se casar, precisa se casar",
        "Precisa se casar, precisa se casar",
        "Precisa se casar, precisa se casar",
        "Precisa se casar, precisa se casar",
        "Precisa se casar, precisa se casar",
    ]
}

export const letras = [
    aguadebeber,chovechuva,aguasdemarco,pelaluzdosolhosteus
];

